# Generated by Django 5.2.8 on 2026-02-02 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('schedulerapp', '0001_initial'),
        ('theaters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='上映開始日時')),
                ('end_time', models.DateTimeField(verbose_name='上映終了日時')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie', verbose_name='映画')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theaters.screen', verbose_name='スクリーン')),
            ],
            options={
                'verbose_name': 'スケジュール',
                'verbose_name_plural': 'スケジュール一覧',
            },
        ),
        migrations.DeleteModel(
            name='Screen',
        ),
        migrations.DeleteModel(
            name='Theater',
        ),
    ]
