# Generated by Django 4.0 on 2026-02-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulerapp', '0002_schedule_delete_screen_delete_theater'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='テンプレート名')),
                ('start_times', models.CharField(help_text='カンマ区切りで入力してください', max_length=255, verbose_name='開始時間リスト')),
                ('pattern_durations', models.CharField(help_text='各枠の映画の長さをカンマ区切りで入力', max_length=255, verbose_name='想定映画時間リスト')),
            ],
            options={
                'verbose_name': 'スケジュールテンプレート',
                'verbose_name_plural': 'スケジュールテンプレート一覧',
            },
        ),
    ]
