# Generated by Django 4.0 on 2026-02-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulerapp', '0003_scheduletemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduletemplate',
            name='limit_runtime',
            field=models.IntegerField(default=120, help_text='この分数以下の映画にこのテンプレートが適用されます', verbose_name='対応可能な最大映画時間(分)'),
        ),
    ]
