# Generated by Django 4.0 on 2026-02-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulerapp', '0004_scheduletemplate_limit_runtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduletemplate',
            name='pattern_durations',
            field=models.TextField(help_text='各枠の映画の長さをカンマ区切りで入力', verbose_name='想定映画時間リスト'),
        ),
        migrations.AlterField(
            model_name='scheduletemplate',
            name='start_times',
            field=models.TextField(help_text='カンマ区切りで入力してください（例: 09:00,09:10...）', verbose_name='開始時間リスト'),
        ),
    ]
