# Generated by Django 4.0 on 2026-02-11 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulerapp', '0005_alter_scheduletemplate_pattern_durations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='上映日'),
        ),
    ]
