# Generated by Django 5.2.8 on 2026-01-30 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='店舗名')),
                ('address', models.CharField(max_length=200, verbose_name='住所')),
                ('total_screens', models.IntegerField(default=0, verbose_name='所有スクリーン数')),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_number', models.IntegerField(verbose_name='シアター番号')),
                ('capacity', models.IntegerField(verbose_name='座席数')),
                ('screen_size', models.CharField(max_length=50, verbose_name='スクリーンサイズ')),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screens', to='theaters.theater', verbose_name='映画館')),
            ],
            options={
                'unique_together': {('theater', 'screen_number')},
            },
        ),
    ]
