# Generated by Django 5.2.8 on 2026-02-04 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theater',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='店舗名'),
        ),
    ]
