# Generated by Django 5.2.8 on 2026-02-08 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0004_theaterassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='テンプレート名（例：超大作5回型）')),
                ('start_times', models.CharField(max_length=255, verbose_name='開始時間リスト')),
                ('description', models.TextField(blank=True, verbose_name='説明・用途')),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theaters.theater', verbose_name='対象映画館')),
            ],
        ),
    ]
