# Generated by Django 5.2.8 on 2026-02-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0005_scheduletemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='screen_rank',
            field=models.IntegerField(default=2, verbose_name='ランク'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='screen_size',
            field=models.CharField(default='Medium', max_length=50, verbose_name='サイズ名'),
        ),
    ]
