# Generated by Django 4.0 on 2026-02-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0006_screen_screen_rank_alter_screen_screen_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='screen_rank',
            field=models.IntegerField(default=2, verbose_name='ランク(1:大 / 2:中 / 3:小)'),
        ),
    ]
