# Generated by Django 4.0 on 2026-02-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0007_alter_screen_screen_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='last_start_time',
            field=models.TimeField(default='21:40', verbose_name='最終上映開始時間'),
        ),
    ]
