# Generated by Django 4.0 on 2026-02-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0008_theater_last_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='opening_time',
            field=models.TimeField(default='09:00', verbose_name='営業開始時間'),
        ),
    ]
