# Generated by Django 5.2.8 on 2026-02-02 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('runtime', models.IntegerField(verbose_name='上映時間(分)')),
                ('release_date', models.DateField(verbose_name='公開日')),
                ('budget', models.BigIntegerField(default=0, verbose_name='予算')),
                ('revenue', models.BigIntegerField(default=0, verbose_name='興行収入')),
                ('company', models.CharField(max_length=100, verbose_name='制作会社')),
                ('language', models.CharField(max_length=10, verbose_name='言語')),
                ('director_name', models.CharField(max_length=100, verbose_name='監督名')),
                ('director_rank', models.FloatField(default=0.0, verbose_name='監督ランクスコア')),
                ('cast1_name', models.CharField(max_length=100, verbose_name='俳優1')),
                ('cast2_name', models.CharField(max_length=100, verbose_name='俳優2')),
                ('cast3_name', models.CharField(max_length=100, verbose_name='俳優3')),
                ('cast_total_score', models.FloatField(default=0.0, verbose_name='キャスト合計スコア')),
                ('is_series', models.BooleanField(default=False, verbose_name='シリーズものか')),
                ('budget_relative_score', models.FloatField(default=0.0)),
                ('is_adventure', models.BooleanField(default=False)),
                ('is_fantasy', models.BooleanField(default=False)),
                ('is_animation', models.BooleanField(default=False)),
                ('is_action', models.BooleanField(default=False)),
                ('is_drama', models.BooleanField(default=False)),
                ('rival_count_is_adventure', models.IntegerField(default=0)),
                ('rival_count_is_animation', models.IntegerField(default=0)),
            ],
        ),
    ]
