# Generated by Django 5.2.8 on 2026-02-02 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='budget_relative_score',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='cast_total_score',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='director_rank',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='revenue',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='rival_count_is_adventure',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='rival_count_is_animation',
        ),
        migrations.AlterField(
            model_name='movie',
            name='is_action',
            field=models.BooleanField(default=False, verbose_name='アクション'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='is_adventure',
            field=models.BooleanField(default=False, verbose_name='アドベンチャー'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='is_animation',
            field=models.BooleanField(default=False, verbose_name='アニメーション'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='is_drama',
            field=models.BooleanField(default=False, verbose_name='ドラマ'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='is_fantasy',
            field=models.BooleanField(default=False, verbose_name='ファンタジー'),
        ),
        migrations.CreateModel(
            name='NowShowingMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_rank', models.FloatField(default=0.0, verbose_name='監督ランクスコア')),
                ('cast_total_score', models.FloatField(default=0.0, verbose_name='キャスト合計スコア')),
                ('budget_relative_score', models.FloatField(default=0.0, verbose_name='予算相対スコア')),
                ('rival_count_is_adventure', models.IntegerField(default=0, verbose_name='ライバル数(アドベンチャー)')),
                ('rival_count_is_animation', models.IntegerField(default=0, verbose_name='ライバル数(アニメ)')),
                ('prediction_score', models.FloatField(default=0.0, verbose_name='AI期待度スコア')),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='movies.movie', verbose_name='対象映画')),
            ],
        ),
    ]
