# Generated by Django 5.2.8 on 2026-02-08 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_nowshowingmovie_budget_cast_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nowshowingmovie',
            name='current_revenue',
            field=models.BigIntegerField(default=0, verbose_name='現在までの累計売上'),
        ),
        migrations.AddField(
            model_name='nowshowingmovie',
            name='predicted_final_revenue',
            field=models.BigIntegerField(default=0, verbose_name='予想最終興行収入'),
        ),
        migrations.AddField(
            model_name='nowshowingmovie',
            name='priority_rank',
            field=models.IntegerField(default=999, verbose_name='計算後優先順位'),
        ),
    ]
