# Generated by Django 5.2.8 on 2026-02-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_nowshowingmovie_current_revenue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nowshowingmovie',
            name='current_week_num',
            field=models.IntegerField(default=1, verbose_name='現在の公開週数'),
        ),
        migrations.AddField(
            model_name='nowshowingmovie',
            name='is_ending_soon',
            field=models.BooleanField(default=1, verbose_name='公開終了フェーズ'),
        ),
    ]
