# Generated by Django 5.2.8 on 2026-02-08 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_nowshowingmovie_current_week_num_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_screen_rank', models.IntegerField(default=1, verbose_name='必須スクリーンランク(1:大 / 2:中 / 3:小)')),
                ('required_daily_runs', models.IntegerField(default=5, verbose_name='1日の最低上映回数')),
                ('contract_period_weeks', models.IntegerField(default=2, verbose_name='契約維持週数（例:2週間）')),
                ('special_notes', models.TextField(blank=True, verbose_name='時間指定などの特記事項')),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='movies.nowshowingmovie', verbose_name='対象映画')),
            ],
        ),
    ]
