# Generated by Django 5.2.8 on 2026-02-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_distributioncontract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributioncontract',
            name='contract_period_weeks',
            field=models.IntegerField(blank=True, null=True, verbose_name='契約維持週数'),
        ),
        migrations.AlterField(
            model_name='distributioncontract',
            name='required_daily_runs',
            field=models.IntegerField(blank=True, null=True, verbose_name='1日の最低上映回数'),
        ),
        migrations.AlterField(
            model_name='distributioncontract',
            name='required_screen_rank',
            field=models.IntegerField(blank=True, null=True, verbose_name='必須スクリーンランク(1:大 / 2:中 / 3:小)'),
        ),
    ]
