# Generated by Django 4.0 on 2026-02-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_distributioncontract_contract_period_weeks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributioncontract',
            name='screening_type',
            field=models.CharField(choices=[('exclusive', 'シアター独占'), ('share', '他作品とシェア'), ('flexible', '指定なし（ランキング順）')], default='flexible', max_length=20, verbose_name='上映形態'),
        ),
    ]
