# Generated by Django 4.0 on 2026-02-09 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0007_alter_screen_screen_rank'),
        ('movies', '0008_distributioncontract_screening_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='nowshowingmovie',
            name='theater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='theaters.theater', verbose_name='映画館'),
        ),
    ]
