# Generated by Django 4.0 on 2026-02-09 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_nowshowingmovie_theater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nowshowingmovie',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
        ),
    ]
