# Generated by Django 4.0 on 2026-02-09 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_alter_nowshowingmovie_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nowshowingmovie',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='now_showings', to='movies.movie'),
        ),
    ]
