# Generated by Django 4.0 on 2026-02-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_alter_nowshowingmovie_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nowshowingmovie',
            name='is_ending_soon',
            field=models.BooleanField(default=False, verbose_name='公開終了フェーズ'),
        ),
        migrations.AlterField(
            model_name='nowshowingmovie',
            name='priority_rank',
            field=models.IntegerField(default=0, verbose_name='計算後優先順位'),
        ),
    ]
